import 'dart:math' as math;

import 'package:antiiq/chaos/chaos_ui/chaos_canvas.dart';
import 'package:flutter/material.dart';

class MusicCanvasDefaults {
  static List<CanvasElement> createElements(Size canvasSize) {
    return [
      CanvasElement(
        id: 'songs',
        title: 'SONGS',
        value: '1247',
        position: Offset(canvasSize.width * 0.40, canvasSize.height * 0.38),
        rotation: -12 * math.pi / 180,
        fontSize: 72,
        color: Colors.white,
      ),
      CanvasElement(
        id: 'albums',
        title: 'ALBUMS',
        value: '89',
        position: Offset(canvasSize.width * 0.60, canvasSize.height * 0.40),
        rotation: 45 * math.pi / 180,
        fontSize: 64,
        color: const Color(0xFFD9B483),
      ),
      CanvasElement(
        id: 'artists',
        title: 'ARTISTS',
        value: '156',
        position: Offset(canvasSize.width * 0.35, canvasSize.height * 0.45),
        rotation: -8 * math.pi / 180,
        fontSize: 68,
        color: const Color(0xFF8BA785),
      ),
      CanvasElement(
        id: 'genres',
        title: 'GENRES',
        value: '23',
        position: Offset(canvasSize.width * 0.60, canvasSize.height * 0.48),
        rotation: 22 * math.pi / 180,
        fontSize: 56,
        color: Colors.red,
      ),
      CanvasElement(
        id: 'playlists',
        title: 'PLAYLISTS',
        value: '12',
        position: Offset(canvasSize.width * 0.36, canvasSize.height * 0.52),
        rotation: -35 * math.pi / 180,
        fontSize: 48,
        color: Colors.blue,
      ),
      CanvasElement(
        id: 'favourites',
        title: 'FAVOURITES',
        value: '78',
        position: Offset(canvasSize.width * 0.58, canvasSize.height * 0.54),
        rotation: 15 * math.pi / 180,
        fontSize: 52,
        color: Colors.pink,
      ),
      CanvasElement(
        id: 'history',
        title: 'HISTORY',
        value: '456',
        position: Offset(canvasSize.width * 0.64, canvasSize.height * 0.60),
        rotation: -18 * math.pi / 180,
        fontSize: 60,
        color: Colors.orange,
      ),
      CanvasElement(
        id: 'smartmix',
        title: 'SMART MIX',
        value: '∞',
        position: Offset(canvasSize.width * 0.40, canvasSize.height * 0.59),
        rotation: 8 * math.pi / 180,
        fontSize: 60,
        color: Colors.purple,
      ),
      CanvasElement(
        id: 'selection',
        title: 'SELECTION',
        value: '∞',
        position: Offset(canvasSize.width * 0.48, canvasSize.height * 0.65),
        rotation: -4 * math.pi / 180,
        fontSize: 56,
        color: Colors.deepOrange,
      ),
    ];
  }

  static List<CanvasElement> createFloatingNumbers(Size canvasSize) {
    return [
      CanvasElement(
        id: 'float_1',
        title: '1247',
        value: '1247',
        position: Offset(canvasSize.width * 0.78, canvasSize.height * 0.34),
        rotation: -5 * math.pi / 180,
        fontSize: 28,
        color: const Color(0xFFD9B483).withValues(alpha: 0.7),
        fontWeight: FontWeight.w100,
        letterSpacing: 1,
      ),
      CanvasElement(
        id: 'float_2',
        title: '89',
        value: '89',
        position: Offset(canvasSize.width * 0.26, canvasSize.height * 0.43),
        rotation: 12 * math.pi / 180,
        fontSize: 28,
        color: Colors.white.withValues(alpha: 0.6),
        fontWeight: FontWeight.w100,
        letterSpacing: 1,
      ),
      CanvasElement(
        id: 'float_3',
        title: '156',
        value: '156',
        position: Offset(canvasSize.width * 0.74, canvasSize.height * 0.56),
        rotation: -8 * math.pi / 180,
        fontSize: 28,
        color: const Color(0xFF8BA785).withValues(alpha: 0.7),
        fontWeight: FontWeight.w100,
        letterSpacing: 1,
      ),
      CanvasElement(
        id: 'float_4',
        title: '23',
        value: '23',
        position: Offset(canvasSize.width * 0.48, canvasSize.height * 0.36),
        rotation: 18 * math.pi / 180,
        fontSize: 24,
        color: Colors.red.withValues(alpha: 0.5),
        fontWeight: FontWeight.w100,
        letterSpacing: 1,
      ),
      CanvasElement(
        id: 'float_5',
        title: '12',
        value: '12',
        position: Offset(canvasSize.width * 0.68, canvasSize.height * 0.44),
        rotation: -15 * math.pi / 180,
        fontSize: 26,
        color: Colors.blue.withValues(alpha: 0.6),
        fontWeight: FontWeight.w100,
        letterSpacing: 1,
      ),
      CanvasElement(
        id: 'float_6',
        title: '78',
        value: '78',
        position: Offset(canvasSize.width * 0.30, canvasSize.height * 0.50),
        rotation: 8 * math.pi / 180,
        fontSize: 25,
        color: Colors.pink.withValues(alpha: 0.55),
        fontWeight: FontWeight.w100,
        letterSpacing: 1,
      ),
      CanvasElement(
        id: 'float_7',
        title: '456',
        value: '456',
        position: Offset(canvasSize.width * 0.70, canvasSize.height * 0.64),
        rotation: -12 * math.pi / 180,
        fontSize: 27,
        color: Colors.orange.withValues(alpha: 0.6),
        fontWeight: FontWeight.w100,
        letterSpacing: 1,
      ),
      CanvasElement(
        id: 'float_8',
        title: '∞',
        value: '∞',
        position: Offset(canvasSize.width * 0.50, canvasSize.height * 0.63),
        rotation: 20 * math.pi / 180,
        fontSize: 30,
        color: Colors.purple.withValues(alpha: 0.5),
        fontWeight: FontWeight.w100,
        letterSpacing: 1,
      ),
      CanvasElement(
        id: 'float_9',
        title: '1247',
        value: '1247',
        position: Offset(canvasSize.width * 0.24, canvasSize.height * 0.58),
        rotation: -6 * math.pi / 180,
        fontSize: 22,
        color: Colors.white.withValues(alpha: 0.4),
        fontWeight: FontWeight.w100,
        letterSpacing: 1,
      ),
      CanvasElement(
        id: 'float_10',
        title: '89',
        value: '89',
        position: Offset(canvasSize.width * 0.82, canvasSize.height * 0.48),
        rotation: 14 * math.pi / 180,
        fontSize: 23,
        color: const Color(0xFFD9B483).withValues(alpha: 0.55),
        fontWeight: FontWeight.w100,
        letterSpacing: 1,
      ),
    ];
  }
}
